version: '3.1'

services:

    spring_boot_postgresql_database:
        image: postgres
        container_name: spring_boot_postgresqldatabase
        environment:
            POSTGRES_DB: spring_boot_database
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - spring_boot_mysql_database_data:/var/lib/mysql

volumes:
    spring_boot_mysql_database_data:
